import 'package:flutter/material.dart';

const Color blackColor = Color(0xFF000000);
const Color redColor = Colors.redAccent;
const Color whiteColor = Color(0xFFFFFFFF);
const Color blueZodiacColor = Color(0xFF13264D);
const Color riverBedBlueColor = Color(0xFF3d4969);
const Color lightGreyColor = Color(0xFFF4F4F4);
const Color mediumGreyColor = Color(0xFFF9F9F9);
const Color transparentColor = Colors.transparent;
const Color roseColor = Color(0xFFBA6873);
const Color darkredColor = Color(0xFFa50000);
const Color darkGreyColor = Color(0xFF323232);
const Color oliveGreenColor = Color(0xFFbdbc64);
const Color tealColor = Color(0xff85c8b4);
const Color frostColor = Color(0xffF2F3D9);
const Color yellowaccent = Color(0xffe8cc5c);
const Color greyColor = Colors.grey;
const Color lightblueColor = Color(0xff6e7790);
const Color yellowColor = Colors.yellowAccent;
const Color frostdarkColor = Color(0xfff8f4dc);
